services:
  backend:
    image: ghcr.io/meticuloushome/meticulous-backend:latest
    container_name: meticulous-backend
    ports:
      - 8080:8080
    expose:
      - 8080
    user: "${USER_ID:-root}:${GROUP_ID:-0}"
    environment:
      - BACKEND=emulation
      - EMULATION_SPEED=100
      - CONFIG_PATH=/app/config
      - LOG_PATH=/app/logs
      - PROFILE_PATH=/app/profiles
      - HISTORY_PATH=/app/history/shots
      - DEBUG_HISTORY_PATH=/app/history/debug
      - UPDATE_PATH=/tmp/firmware
      - ZEROCONF_OVERWRITE=192.168.2.11/24,Mimoja-Datenschleuder
      - PORT=8080
      - DEFAULT_IMAGES=/app/images/default
      - IMAGES_PATH=/app/images/profile-images
      - SYSTEM_SOUNDS=/app/sounds/
    volumes:
      - ./userdata/config:/app/config
      - ./userdata/logs:/app/logs
      - ./userdata/profiles:/app/profiles
      - ./userdata/shots:/app/history
      - ./userdata/images:/app/images/profile-images
